server:
  port: 8087

spring:
  application:
    name: fitness-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:fitnessdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driverClassName: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: ${SPRING_JPA_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
