server:
  port: 8087

spring:
  application:
    name: fitness-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fitwell_fitness_db
    driver-class-name: org.postgresql.Driver
    username: fitwell_admin
    password: FitWell@123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true